# Adapted from https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Create jars
        run: (cd mkjars-script/ && python mk_jars.py)
      - name: Build and Test
        run: (cd rattlesnake-compiler/ && sbt -v +test)